# Generated by Django 5.0.1 on 2024-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
    ]
