# Generated by Django 4.2.6 on 2024-01-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_emailuser_email_verified_emailuser_token_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='token_created_at',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='verification_token',
        ),
    ]
