# Generated by Django 5.0.1 on 2024-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
