# Generated by Django 4.2.6 on 2024-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_remove_superusercredentials_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superusercredentials',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
