# Generated by Django 4.2.6 on 2024-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_chatthread_alter_chatmessage_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperuserCredentials',
        ),
    ]
